{% set name = "polyagamma" %}
{% set version = "1.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyagamma-{{ version }}.tar.gz
  sha256: 0b823b4b386fc7ac5e1a1829b123eaefe881bce078240693c209a30b9da3d7b2

build:
  number: 1
  script: {{ PYTHON }} setup.py build_ext --inplace && {{ PYTHON }} -m pip install . -vv
  skip: True  # [py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cython <3.0.0                          # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - numpy
    - cython 0.29.36
    - wheel
    - setuptools >=61.0.0
    - setuptools-scm
  run:
    - python

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "from polyagamma import random_polyagamma;print(random_polyagamma())"
  requires:
    - pip

about:
  home: https://github.com/zoj613/polyagamma/
  summary: Efficiently generate samples from the Polya-Gamma distribution using a NumPy/SciPy compatible interface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zoj613
