{% set name = "polyagamma" %}
{% set version = "1.3.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyagamma-{{ version }}.tar.gz
  sha256: 3cc05854c51464e193d092db0235f8340f42a8b3808e8320e2a1910434efe27c

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy
    - poetry  >=1.1.4
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "from polyagamma import random_polyagamma;print(random_polyagamma())"
  requires:
    - pip

about:
  home: https://github.com/zoj613/polyagamma/
  summary: Efficiently generate samples from the Polya-Gamma distribution using a NumPy/SciPy compatible interface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zoj613
