{% set name = "polyagamma" %}
{% set version = "1.3.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/polyagamma-{{ version }}.tar.gz
  sha256: 610d1548ae8a33765d44247998dd21866aeda091bba92bbd55aba40d8e75faf2

build:
  number: 0
  skip: true  # [py>=40 or py<36]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy 1.19.*
    - poetry  >=1.1.4
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - {{ name }}
  commands:
    - pip check
    - python -c "from polyagamma import random_polyagamma;print(random_polyagamma())"
  requires:
    - pip

about:
  home: https://github.com/zoj613/polyagamma/
  summary: Efficiently generate samples from the Polya-Gamma distribution using a NumPy/SciPy compatible interface.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - zoj613
